### ISSUE TITLE
报错TypeError: string indices must be integers

### ISSUE THREAD

**Issue by weincui** [nautilis/plugin_music#2]
[ERROR][2023-07-06 19:39:18][chat_channel.py:273] - Worker return exception: string indices must be integers
Traceback (most recent call last):
  File "/root/.conda/envs/we/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 149, in _handle
    reply = self._generate_reply(context)
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 159, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/root/chatgpt-on-wechat/plugins/plugin_manager.py", line 165, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/root/chatgpt-on-wechat/plugins/plugin_music/netease_music.py", line 52, in on_handle_context
    url, name, ar = self.search_song(msg)
  File "/root/chatgpt-on-wechat/plugins/plugin_music/netease_music.py", line 102, in search_song
    songs = result["songs"]
TypeError: string indices must be integers

**Comment by RootSherry** [comment]
我也是这个问题，你解决了吗

**Comment by moli-xia** [comment]
一个样，不知道啥情况
