### ISSUE TITLE
docker部署

### ISSUE THREAD

**Issue by Simon6088** [nautilis/plugin_music#5]
2024-04-17 11:48:09 [INFO][2024-04-17 03:48:09][netease_music.py:42] - content => music 点歌: 可惜我是水瓶座-杨千嬅
2024-04-17 11:48:09 ERROR:root:search song buss code:50000005, resp:{'code': 50000005}
2024-04-17 11:48:09 可惜我是水瓶座
2024-04-17 11:48:09 杨千嬅
2024-04-17 11:48:09 200
2024-04-17 11:48:09 [ERROR][2024-04-17 03:48:09][chat_channel.py:301] - Worker return exception: 'NoneType' object is not subscriptable
2024-04-17 11:48:09 Traceback (most recent call last):
2024-04-17 11:48:09   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-04-17 11:48:09     result = self.fn(*self.args, **self.kwargs)
2024-04-17 11:48:09   File "/app/channel/chat_channel.py", line 170, in _handle
2024-04-17 11:48:09     reply = self._generate_reply(context)
2024-04-17 11:48:09   File "/app/channel/chat_channel.py", line 180, in _generate_reply
2024-04-17 11:48:09     e_context = PluginManager().emit_event(
2024-04-17 11:48:09   File "/app/plugins/plugin_manager.py", line 189, in emit_event
2024-04-17 11:48:09     instance.handlers[e_context.event](e_context, *args, **kwargs)
2024-04-17 11:48:09   File "/app/plugins/plugin_music/netease_music.py", line 52, in on_handle_context
2024-04-17 11:48:09     url, name, ar = self.search_song(msg)
2024-04-17 11:48:09   File "/app/plugins/plugin_music/netease_music.py", line 99, in search_song
2024-04-17 11:48:09     if resp["code"] == 200:
2024-04-17 11:48:09 TypeError: 'NoneType' object is not subscriptable

**Comment by Simon6088** [comment]
ERROR:root:search song buss code:50000005, resp:{'code': 50000005}
